// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Screenfull: typeof import('./components/screenfull/index.vue')['default']
    SvgIcon: typeof import('./components/svg-icon/index.vue')['default']
    ThemeSwitch: typeof import('./components/theme-switch/index.vue')['default']
  }
}

export { }
